name: Deploy to Vercel Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Vercel project
        run: |
          mkdir -p .vercel
          echo '{"projectId":"prj_deXVgajit4zSb9zyywQUGJ68JUJ5","orgId":"team_cWnfT04zxR7EtI5Loc369u9t"}' > .vercel/project.json

      - name: Deploy to Vercel
        run: npx vercel@33 deploy --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
