name: Deploy to Vercel Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: team_cWnfT04zxR7EtI5Loc369u9t
      VERCEL_PROJECT_ID: prj_deXVgajit4zSb9zyywQUGJ68JUJ5
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        run: npx vercel deploy --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
